# Generated by Django 5.1.1 on 2024-10-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento y Cotizaciones'), ('minutas', 'Minutas'), ('reglamentos', 'Reglamentos'), ('otros', 'Otros')], max_length=50),
        ),
    ]
