# Generated by Django 5.1.1 on 2025-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_monthlyfees_extra_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento y Cotizaciones'), ('pagos_mantenimiento', 'Pagos de Mantenimiento'), ('gastos_pasivos', 'Gastos y Pasivos'), ('minutas', 'Minutas'), ('reglamentos', 'Reglamentos'), ('reportes', 'Reportes')], max_length=50),
        ),
    ]
